services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    image: ${DOCKERHUB_USERNAME}/backend:latest
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      LOG_PATH: /shared/requests.log
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - shared:/shared
    ports:
      - "5000:5000"

  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend

  logger:
    image: ${DOCKERHUB_USERNAME}/logger:latest
    volumes:
      - shared:/shared

volumes:
  pgdata:
  shared:
